### PR TITLE
Updating distributing key-value for newer mochi components

### PR DESCRIPTION
**Pull request by brobey**
This updates the distributed key-value package for changes in ssg and other Mochi components

### CODE REVIEW

**Comment by mdorier** [comment]
You might want to look at the update I did to mochi-sdskv, the API has changed a bit, so your code will break with mochi-sdskv@main.

**Comment by shanedsnyder** [comment]
The SSG API will be changing soon on master, so I can try to resync this code to account for those changes, too, but I'm not any use beyond ensuring things compile here :)

**Comment by brobey** [comment]
Let me know when you put it in and I’ll sync things up.

From: shanedsnyder ***@***.***>
Reply-To: mochi-hpc/mochi-sdsdkv ***@***.***>
Date: Tuesday, April 27, 2021 at 8:08 AM
To: mochi-hpc/mochi-sdsdkv ***@***.***>
Cc: Robert Robey ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL] Re: [mochi-hpc/mochi-sdsdkv] Updating distributing key-value for newer mochi components (#2)


The SSG API will be changing soon on master, so I can try to resync this code to account for those changes, too, but I'm not any use beyond ensuring things compile here :)

**Comment by brobey** [comment]
I was looking at the changes yesterday with Donnie. I’ll try to resync.

From: Matthieu Dorier ***@***.***>
Reply-To: mochi-hpc/mochi-sdsdkv ***@***.***>
Date: Tuesday, April 27, 2021 at 2:35 AM
To: mochi-hpc/mochi-sdsdkv ***@***.***>
Cc: Robert Robey ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL] Re: [mochi-hpc/mochi-sdsdkv] Updating distributing key-value for newer mochi components (#2)


You might want to look at the update I did to mochi-sdskv, the API has changed a bit, so your code will break with ***@***.***

**Pull request merged**
